### PR TITLE
Use new mechanism to disable plugin

### PR DESCRIPTION
**Pull request by theseion**
Updated readme

### CODE REVIEW

**Comment by dune73** [comment]
Looks good. Thank you. Merging now.

**Comment by theseion** [comment]
You didn't merge :) I there a reason or did you just forget?

**Comment by dune73** [comment]
I knew I was going to forget to press merge in one of those. Thanks for checking.

**Comment by lifeforms** [comment]
Thanks for handling these @dune73 🥳

**Pull request merged**
