### PR TITLE
fix: name of cookies changed

### PR DESCRIPTION
**Pull request by azurit**
Name of cookies has changed, see https://github.com/phpmyadmin/phpmyadmin/pull/19141.

### CODE REVIEW

**Comment by williamdes** [comment]
I am not sure the rule is even correct before, or it was not supporting https 🤔 ?
Here is a before and after (prefixed with` __Secure`) both cookies set in my browser
image

**Comment by azurit** [comment]
These cookies are covered by lines without specific cookie name, for example:
`ctl:ruleRemoveTargetById=942370;REQUEST_COOKIES,\`

These applies to all cookies, no matter on name.

**Comment by williamdes** [comment]
> These cookies are covered by lines without specific cookie name, for example: `ctl:ruleRemoveTargetById=942370;REQUEST_COOKIES,\`
> 
> These applies to all cookies, no matter on name.

Then I am not sure to understand why there is two names stated here ?
Can you help me understand please

**Comment by azurit** [comment]
These lines are covering whitelist for all cookies for a specified rules (see different numbers - IDs):
```
    ctl:ruleRemoveTargetById=932200;REQUEST_COOKIES,\
    ctl:ruleRemoveTargetById=941100;REQUEST_COOKIES,\
    ctl:ruleRemoveTargetById=941100;REQUEST_COOKIES,\
    ctl:ruleRemoveTargetById=941120;REQUEST_COOKIES,\
    ctl:ruleRemoveTargetById=941120;REQUEST_COOKIES,\
    ctl:ruleRemoveTargetById=942200;REQUEST_COOKIES,\
    ctl:ruleRemoveTargetById=942200;REQUEST_COOKIES,\
    ctl:ruleRemoveTargetById=942340;REQUEST_COOKIES,\
    ctl:ruleRemoveTargetById=942340;REQUEST_COOKIES,\
    ctl:ruleRemoveTargetById=942370;REQUEST_COOKIES,\
    ctl:ruleRemoveTargetById=942370;REQUEST_COOKIES,\

```
These lines are covering whitelist only for specified cookie names for a specified rules (different than the rules above):
```
    ctl:ruleRemoveTargetById=942100;REQUEST_COOKIES:auto_saved_sql,\
    ctl:ruleRemoveTargetById=942100;REQUEST_COOKIES:auto_saved_sql,\
    ctl:ruleRemoveTargetById=942260;REQUEST_COOKIES:pma_console_config"
    ctl:ruleRemoveTargetById=942100;REQUEST_COOKIES:__Secure-auto_saved_sql,\
    ctl:ruleRemoveTargetById=942260;REQUEST_COOKIES:pma_console_config,\
    ctl:ruleRemoveTargetById=942260;REQUEST_COOKIES:__Secure-pma_console_config"
```

**Pull request merged**
